Formatted desktop version
emyrue/Portfolio pull request #4
Opened 2022-02-16 22:42 UTC by emyrue

- Added media queries
- Added images
- Added menu items
- Used display: grid

2022-02-16 23:46 UTC, gemmen29 requested changes
Hi @emyrue, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 23:46 UTC, gemmen29 commented on index.html
>          <section class="project project1">
Please try to match the Figma design in width 993px for the projects and about sections.
| Your design | Figma design |
| --- | --- |
| ![screencapture-raw-githack-emyrue-Portfolio-form-index-html-2022-02-17-01_25_45](https://user-images.githubusercontent.com/24703171/154375289-29eff66a-70ab-4488-91c7-fcc42d7ccc0b.png) | ![Template 8-main](https://user-images.githubusercontent.com/24703171/154375261-638a6ffd-f8a7-4f12-97a7-bafcbea2a853.png) |

And in width 992px the image that takes class `banner2` disappear and this is how the page looks like:
![screencapture-raw-githack-emyrue-Portfolio-form-index-html-2022-02-17-01_38_25](https://user-images.githubusercontent.com/24703171/154375896-4b6da155-5a4c-4cb0-9eb1-2def5580114f.png)

2022-02-16 23:46 UTC, gemmen29 commented on index.html
>              <form class="form" action="https://formspree.io/f/mjvlwyao" method="POST">
Please try to match the Figma design in a mobile version for the email input
| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/154376433-36851eca-a92b-4c18-bef9-565b25e5323e.png) | ![image](https://user-images.githubusercontent.com/24703171/154376482-77193438-fd4f-4c09-a50f-c35e5d620119.png) |

2022-02-17 17:17 UTC, elmar8287 approved these changes
Hi, @emyrue,

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

## [OPTIONAL] Before merging, please fix the space after the footer in the desktop version. 
<img width="505" alt="Screen Shot 2022-02-17 at 21 16 19" src="https://user-images.githubusercontent.com/49064106/154535333-24f6cecb-8e56-437e-a35f-8329a477aa36.png">


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 17:39 UTC, merged